language: node_js
node_js:
  - 4.4.7
script:
  - npm run lint
  - npm run test
after_script:
  - "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
branches:
  only:
    - master